#!/usr/bin/env node
/**
 * check-links.mjs — zero-dependency link checker for the Attio Workflows Handbook.
 *
 * Scans every .md/.mdx file under src/content/docs/ for markdown links, bare
 * URLs, and frontmatter `link:` values (Starlight hero actions), then:
 *
 *   Internal links (starting with "/") are resolved against the content tree:
 *     /reference/records/create-record/  ->  src/content/docs/reference/records/create-record.md
 *     also accepts .mdx and index files  ->  .../create-record/index.{md,mdx}
 *     and files under public/ (assets). Anchors/queries are stripped;
 *     /llms*.txt (generated by starlight-llms-txt) is ignored.
 *
 *   External links (http/https) are deduplicated and checked with HEAD, then
 *   GET as a fallback. A real-browser User-Agent is MANDATORY: attio.com
 *   returns 404 to non-browser user agents, so naive checkers false-positive.
 *
 * Status handling for external URLs:
 *   200-399                       OK
 *   403 / 429                     warn (blocked, not broken) — does not fail
 *   404 / 410 / 5xx / net error   broken — fails the run
 *   anything else (401, 405, …)   warn — does not fail
 *
 * Flags:
 *   --internal-only   skip all network checks (used in CI on every push/PR)
 *
 * Exit code 1 only when broken internal or broken external links are found.
 * Warnings never fail the run.
 */

import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS_DIR = path.join(ROOT, 'src', 'content', 'docs');
const PUBLIC_DIR = path.join(ROOT, 'public');

const USER_AGENT =
	'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';
const TIMEOUT_MS = 10_000;
const CONCURRENCY = 8;

const INTERNAL_ONLY = process.argv.includes('--internal-only');

// ---------------------------------------------------------------------------
// File discovery
// ---------------------------------------------------------------------------

/** Recursively collect files under dir, returned as posix-style paths relative to dir. */
function walk(dir, base = dir, out = []) {
	if (!existsSync(dir)) return out;
	for (const entry of readdirSync(dir)) {
		if (entry.startsWith('.')) continue; // .DS_Store etc.
		const full = path.join(dir, entry);
		if (statSync(full).isDirectory()) {
			walk(full, base, out);
		} else {
			out.push(path.relative(base, full).split(path.sep).join('/'));
		}
	}
	return out;
}

const docFiles = walk(DOCS_DIR).filter((p) => p.endsWith('.md') || p.endsWith('.mdx'));
// Sets of real paths so lookups are case-sensitive even on macOS (matches Linux CI).
const docPaths = new Set(docFiles);
const publicPaths = new Set(walk(PUBLIC_DIR));

// ---------------------------------------------------------------------------
// Link extraction
// ---------------------------------------------------------------------------

/** Replace fenced code blocks and inline code spans with spaces, preserving offsets. */
function maskCode(content) {
	const lines = content.split('\n');
	let inFence = false;
	let fenceMarker = '';
	const masked = lines.map((line) => {
		const fence = line.match(/^\s*(```|~~~)/);
		if (fence && !inFence) {
			inFence = true;
			fenceMarker = fence[1];
			return ' '.repeat(line.length);
		}
		if (inFence) {
			if (fence && fence[1] === fenceMarker) inFence = false;
			return ' '.repeat(line.length);
		}
		// Inline code spans on non-fenced lines.
		return line.replace(/`[^`]*`/g, (m) => ' '.repeat(m.length));
	});
	return masked.join('\n');
}

function lineOf(content, index) {
	let line = 1;
	for (let i = 0; i < index; i++) if (content[i] === '\n') line++;
	return line;
}

/** Trim punctuation that is prose, not part of the URL. */
function trimBareUrl(url) {
	return url.replace(/[.,;:!?'"]+$/, '');
}

/**
 * Extract all link occurrences from one file.
 * Returns [{ target, line }].
 */
function extractLinks(content) {
	const masked = maskCode(content);
	const found = [];
	const coveredRanges = [];

	// 1. Inline markdown links and images: [text](/path/) or [text](<url> "title")
	const inlineRe = /!?\[[^\]]*\]\(\s*<?([^)<>\s]+)>?[^)]*\)/g;
	for (const m of masked.matchAll(inlineRe)) {
		found.push({ target: m[1], line: lineOf(masked, m.index) });
		coveredRanges.push([m.index, m.index + m[0].length]);
	}

	// 2. Reference-style definitions: [label]: /path/
	const refRe = /^[ \t]*\[[^\]]+\]:\s+(\S+)/gm;
	for (const m of masked.matchAll(refRe)) {
		found.push({ target: m[1], line: lineOf(masked, m.index) });
		coveredRanges.push([m.index, m.index + m[0].length]);
	}

	// 3. Bare URLs anywhere else (prose, frontmatter, HTML attributes).
	const bareRe = /\bhttps?:\/\/[^\s<>()[\]"'`*]+/g;
	for (const m of masked.matchAll(bareRe)) {
		const inCovered = coveredRanges.some(([s, e]) => m.index >= s && m.index < e);
		if (inCovered) continue;
		const target = trimBareUrl(m[0]);
		if (target.length > 'https://'.length) {
			found.push({ target, line: lineOf(masked, m.index) });
		}
	}

	// 4. Frontmatter `link:` values (Starlight hero actions use root-relative paths).
	const fm = content.match(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/);
	if (fm) {
		const fmRegion = content.slice(0, fm[0].length);
		const linkRe = /^[ \t-]*link:\s*['"]?([^\s'"]+)['"]?/gm;
		for (const m of fmRegion.matchAll(linkRe)) {
			if (m[1].startsWith('/')) {
				found.push({ target: m[1], line: lineOf(content, m.index) });
			}
		}
	}

	return found;
}

// ---------------------------------------------------------------------------
// Internal resolution
// ---------------------------------------------------------------------------

function checkInternal(target) {
	// Strip anchor and query string.
	const clean = target.split('#')[0].split('?')[0];
	if (clean === '') return { ok: true }; // pure anchor like "/page/#x" already handled; "#x" filtered earlier
	const p = clean.replace(/^\/+/, '').replace(/\/+$/, '');

	// Generated by starlight-llms-txt at build time; not in the content tree.
	if (/^llms[^/]*\.txt$/.test(p)) return { ok: true };

	const candidates =
		p === ''
			? ['index.md', 'index.mdx']
			: [`${p}.md`, `${p}.mdx`, `${p}/index.md`, `${p}/index.mdx`];

	if (candidates.some((c) => docPaths.has(c))) return { ok: true };
	if (p !== '' && publicPaths.has(p)) return { ok: true }; // static asset

	return {
		ok: false,
		reason: `no matching page (tried ${p === '' ? 'index.{md,mdx}' : `${p}.{md,mdx} and ${p}/index.{md,mdx}`} under src/content/docs/, and public/${p})`,
	};
}

// ---------------------------------------------------------------------------
// External checking
// ---------------------------------------------------------------------------

async function fetchStatus(url, method) {
	const res = await fetch(url, {
		method,
		redirect: 'follow',
		headers: {
			'user-agent': USER_AGENT,
			accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
			'accept-language': 'en-US,en;q=0.9',
		},
		signal: AbortSignal.timeout(TIMEOUT_MS),
	});
	// Don't download bodies; release the connection.
	try {
		await res.body?.cancel();
	} catch {
		/* ignore */
	}
	return res.status;
}

/** Returns { level: 'ok' | 'warn' | 'broken', detail }. */
async function checkExternal(url) {
	let status = null;
	let lastError = null;

	for (const method of ['HEAD', 'GET']) {
		try {
			status = await fetchStatus(url, method);
			lastError = null;
			if (status >= 200 && status < 400) return { level: 'ok', detail: `HTTP ${status}` };
			// Some servers reject HEAD outright — always retry once with GET.
		} catch (err) {
			lastError = err;
			status = null;
		}
	}

	if (lastError) {
		const detail =
			lastError.name === 'TimeoutError'
				? `timed out after ${TIMEOUT_MS / 1000}s`
				: `network error: ${lastError.cause?.message ?? lastError.message}`;
		return { level: 'broken', detail };
	}
	if (status === 404 || status === 410 || status >= 500) {
		return { level: 'broken', detail: `HTTP ${status}` };
	}
	if (status === 403 || status === 429) {
		return { level: 'warn', detail: `HTTP ${status} (blocked, not broken)` };
	}
	return { level: 'warn', detail: `HTTP ${status} (unexpected status)` };
}

/** Run worker over items with bounded concurrency. */
async function pool(items, limit, worker) {
	const results = new Array(items.length);
	let next = 0;
	const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
		while (next < items.length) {
			const i = next++;
			results[i] = await worker(items[i]);
		}
	});
	await Promise.all(runners);
	return results;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
	if (!existsSync(DOCS_DIR)) {
		console.error(`Docs directory not found: ${DOCS_DIR}`);
		process.exit(1);
	}

	// issuesByFile: relPath -> [{ line, target, level, detail }]
	const issuesByFile = new Map();
	const addIssue = (file, issue) => {
		if (!issuesByFile.has(file)) issuesByFile.set(file, []);
		issuesByFile.get(file).push(issue);
	};

	// externalOccurrences: url -> [{ file, line }]
	const externalOccurrences = new Map();

	let internalCount = 0;
	let brokenInternal = 0;

	for (const relPath of docFiles) {
		const content = readFileSync(path.join(DOCS_DIR, relPath), 'utf8');
		const file = `src/content/docs/${relPath}`;

		for (const { target, line } of extractLinks(content)) {
			if (/^https?:\/\//.test(target)) {
				if (!externalOccurrences.has(target)) externalOccurrences.set(target, []);
				externalOccurrences.get(target).push({ file, line });
			} else if (target.startsWith('/')) {
				internalCount++;
				const result = checkInternal(target);
				if (!result.ok) {
					brokenInternal++;
					addIssue(file, { line, target, level: 'broken', detail: result.reason });
				}
			}
			// Anything else (anchors, mailto:, relative paths) is out of scope.
		}
	}

	let brokenExternal = 0;
	let warnExternal = 0;
	const externalUrls = [...externalOccurrences.keys()].sort();

	if (!INTERNAL_ONLY && externalUrls.length > 0) {
		console.log(`Checking ${externalUrls.length} unique external URLs (concurrency ${CONCURRENCY}, ${TIMEOUT_MS / 1000}s timeout)...\n`);
		const results = await pool(externalUrls, CONCURRENCY, checkExternal);
		results.forEach((result, i) => {
			if (result.level === 'ok') return;
			const url = externalUrls[i];
			if (result.level === 'broken') brokenExternal++;
			else warnExternal++;
			for (const { file, line } of externalOccurrences.get(url)) {
				addIssue(file, { line, target: url, level: result.level, detail: result.detail });
			}
		});
	}

	// -------------------------------------------------------------------------
	// Report, grouped by file
	// -------------------------------------------------------------------------

	const sortedFiles = [...issuesByFile.keys()].sort();
	for (const file of sortedFiles) {
		console.log(file);
		const issues = issuesByFile.get(file).sort((a, b) => a.line - b.line);
		for (const { line, target, level, detail } of issues) {
			const mark = level === 'broken' ? 'BROKEN' : 'WARN  ';
			console.log(`  ${mark}  line ${String(line).padStart(4)}  ${target}`);
			console.log(`          ${detail}`);
		}
		console.log('');
	}

	// -------------------------------------------------------------------------
	// Summary
	// -------------------------------------------------------------------------

	console.log('--- Summary ---');
	console.log(`Files scanned:        ${docFiles.length}`);
	console.log(`Internal links:       ${internalCount} (${brokenInternal} broken)`);
	if (INTERNAL_ONLY) {
		console.log(`External URLs:        ${externalUrls.length} unique (skipped: --internal-only)`);
	} else {
		console.log(`External URLs:        ${externalUrls.length} unique (${brokenExternal} broken, ${warnExternal} warnings)`);
	}

	const failed = brokenInternal > 0 || brokenExternal > 0;
	if (failed) {
		console.log('\nResult: FAIL (broken links found)');
	} else if (warnExternal > 0) {
		console.log('\nResult: PASS with warnings (blocked URLs are not treated as broken)');
	} else {
		console.log('\nResult: PASS');
	}
	process.exit(failed ? 1 : 0);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
